<?xml version="1.0" encoding="ISO-8859-1"?>
<definitions targetNamespace="process.wsdl" name="OrdersService"
    xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"
    xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:tns="process.wsdl"
>
    <types>
        <xsd:schema targetNamespace="urn:processwsdl">
            <xsd:import namespace="http://schemas.xmlsoap.org/soap/encoding/"/>
            <xsd:import namespace="http://schemas.xmlsoap.org/wsdl/"/>
            <xsd:complexType name="PROCESSArray">
                <xsd:complexContent>
                <xsd:restriction base="SOAP-ENC:Array">
                    <xsd:attribute ref="SOAP-ENC:arrayType" wsdl:arrayType="xsd:string[]" />
                </xsd:restriction>
                </xsd:complexContent>
            </xsd:complexType>
        </xsd:schema>
    </types>

    <message name="PROCESSResponse"><part name="return" type="xsd:PROCESSArray"/></message>
    <portType name="PROCESSPortType">
        <operation name="process">
            <output message="tns:PROCESSResponse"/>
        </operation>
    </portType>

    <binding name="PROCESSBinding" type="tns:PROCESSPortType">
        <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="process">
            <soap:operation soapAction="urn:arnleadservicewsdl#process" style="rpc"/>
            <input>
                <soap:body use="encoded" namespace="urn:processwsdl" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" />
            </input>
            <output>
                <soap:body use="encoded" namespace="urn:processwsdl" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" />
            </output>
        </operation>
    </binding>

    <service name="PROCESSService">
        <port name="PROCESSPort" binding="tns:PROCESSBinding">
            <soap:address location="http://localhost:8089/process"/>
        </port>
    </service>
</definitions>